pub const RETRYING_STOP_ATTEMPTS: &'static str = "RETRYING__STOP__ATTEMPTS";
pub const RETRYING_STOP_DURATION: &'static str = "RETRYING__STOP__DURATION";
pub const RETRYING_WAIT_FIXED: &'static str = "RETRYING__WAIT__FIXED";
pub const RETRYING_WAIT_RANDOM_MIN: &'static str = "RETRYING__WAIT__RANDOM__MIN";
pub const RETRYING_WAIT_RANDOM_MAX: &'static str = "RETRYING__WAIT__RANDOM__MAX";
pub const RETRYING_WAIT_EXPONENTIAL_MULTIPLIER: &'static str =
    "RETRYING__WAIT__EXPONENTIAL__MULTIPLIER";
pub const RETRYING_WAIT_EXPONENTIAL_MIN: &'static str = "RETRYING__WAIT__EXPONENTIAL__MIN";
pub const RETRYING_WAIT_EXPONENTIAL_MAX: &'static str = "RETRYING__WAIT__EXPONENTIAL__MAX";
pub const RETRYING_WAIT_EXPONENTIAL_EXP_BASE: &'static str =
    "RETRYING__WAIT__EXPONENTIAL__EXP_BASE";
